language: elixir
elixir:
- 1.9.1
env:
  MIX_ENV: test
otp_release:
  - '21.3'
install:
- mix local.rebar --force
- mix local.hex --force
- mix deps.get
script:
  - mix deps.compile
  - mix compile
  - mix fformat --check-formatted
  - mix credo --strict
  - mix test
  - mix coveralls.travis --pro
  - mix dialyzer --halt-exit-status
cache:
  directories:
  - _build
  - deps
